### ISSUE TITLE
Changelog, please

### ISSUE THREAD

**Issue by knightq** [mynameisrufus/sorted-activerecord#3]
Can you kindly add a CHANGELOG for the future releases.

**Comment by mynameisrufus** [comment]
Hmm did something break? Are you using a `~>` version in Gemfile?

**Comment by knightq** [comment]
No, it's just a matter of clarity ;-)

Do you strictly adhere [semantic versioning](http://semver.org/)?
I don't know, so - without a changelog - the only way I have to proactively check for gem potential problems on update is to compare two tags and manually try to understand if any breaking change has been introduced on the new version.

That's all :-)

PS: in this case, is it safe to upgrade from 0.1.2 to 0.1.3? (if you are following the semantic versioning convention, it should...)

**Comment by mynameisrufus** [comment]
Looking at https://github.com/mynameisrufus/sorted-activerecord/commit/11e63671989e52b7f1b622363c5df5626afdf95b I think it's a patch version change. TBH I don't even use this gem and have not for a couple of years but maintain it anyway for posterity. Would you like to maintain this repo?

**Comment by knightq** [comment]
I think this too...
Thank you, I would, since we are currently using this gem and we need it as updated as possible

**Comment by mynameisrufus** [comment]
Let me know when you want me to release a new Gem :+1:

**Comment by knightq** [comment]
Hi Rufus,

I’ve added the CHANGELOG (and updated Version).
No need to release a new version for this, thank you! 

Andrea Salicetti
Partner & Platform Engineer @ Blomming.com
andrea.salicetti@gmail.com mailto:andrea.salicetti@gmail.com
 <>  http://it.linkedin.com/in/andreasalicetti  http://twitter.com/#!/asalicetti  https://github.com/knightq  http://stackoverflow.com/users/390534/andrea-salicetti  http://www.delicious.com/andrea.salicetti 
 BLOMMING http://blomming.com/
The Social eCommerce
